# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'Android', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kirigami': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'libraries/kirigami-addons': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kcolorscheme': '@latest-kf6'
    'pim/kmime': '@latest-kf6'

 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/kcrash': '@latest-kf6'

Options:
 require-passing-tests-on: ['@all']
